### ISSUE TITLE
Login Interface

### ISSUE THREAD

**Issue by anmolbhutada** [CapstoneProject18/Data-streaming-through-Apache-Storm-and-Spark#1]
As a user, when I visit the web-app I should be able to see a welcome screen with a login form. The login form should have the option for Sign-in, Sign-up and forgotten password. The form should show 2 fields initially viz, Username and Password.

Tasks
The Username and Password field should have placeholders stating what to do in those fields. 
The Username and Password should be stored in a database and the password should be hashed before it is stored.
If user has made 3 unsuccessful login attempts then either a verification mail should be sent to his account or his account should be blocked for a temporary time period.
The inputs entered in the field should be sanitized.

**Comment by shah-naman** [comment]
[login.zip](https://github.com/CapstoneProject18/Data-streaming-through-Apache-Storm-and-Spark/files/2587979/login.zip)
This is the code for the login attempt.
