### ISSUE TITLE
Integration of Apache Storm

### ISSUE THREAD

**Issue by anmolbhutada** [CapstoneProject18/Data-streaming-through-Apache-Storm-and-Spark#12]
As a user, when I want to make a search or any other query I want it to be quick.

Integrate Apache Storm to manage the data through the distributed file systems. Apache storm should be linked with all the queries, searches, and the functionalities to make all the calls made faster and much more effective.
 
All the data calculations and the real-time data streaming is to be done using Apache Storm.

**Comment by Manisha-Baheti** [comment]
[Readme.docx](https://github.com/CapstoneProject18/Data-streaming-through-Apache-Storm-and-Spark/files/2615951/Readme.docx)

**Comment by Manisha-Baheti** [comment]
This zip file contains all the necessary code files and guide/readme to integrate Apache spark into our Web Application.
[Issue-Apache Storm Integration.zip](https://github.com/CapstoneProject18/Data-streaming-through-Apache-Storm-and-Spark/files/2616059/Issue-Apache.Storm.Integration.zip)
